name = "FixArgs"
uuid = "5d8a8d4b-09a6-4f10-9cda-cb42fab7536d"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.4"
